import { useRef, useState, type CSSProperties } from 'react';

// Task 36a - dev-only listening page for the crowd sound set generated by
// dev/generate-crowd-sfx.ts into client/public/crowd/ (gitignored - Argyrios
// runs that script himself, so this directory may be empty; the loops just
// won't decode until it's populated). No socket, no room, no server.
//
// The crowd is a RAMP: three loops (murmur/unrest/roar) play simultaneously
// and continuously, mixed by one intensity number 0-1 with an equal-power
// crossfade across three zones - murmur alone at 0, unrest full at .5, roar
// alone at 1 - plus four one-shots layered on top at gain = max(intensity,
// .3). This page only lets you LISTEN to that mix; real playback wiring is
// Task 36b.
const LOOP_NAMES = ['murmur', 'unrest', 'roar'] as const;
type LoopName = (typeof LOOP_NAMES)[number];

const ONE_SHOTS = ['cheer-small', 'cheer-big', 'boo-small', 'boo-big'] as const;
type OneShotName = (typeof ONE_SHOTS)[number];

const DUCK_TARGET = 0.12;
const DUCK_MS = 300;
const ONE_SHOT_MIN_GAIN = 0.3;

// Equal-power crossfade across two adjacent zones of a 3-point ramp
// (murmur -> unrest -> roar). `t` is the local position within the active
// zone, 0..1; equal-power means cos/sin rather than a linear ramp, so the
// perceived loudness stays constant through the crossfade.
function zoneGains(intensity: number): Record<LoopName, number> {
  const clamped = Math.min(1, Math.max(0, intensity));
  if (clamped <= 0.5) {
    const t = clamped / 0.5;
    const angle = t * (Math.PI / 2);
    return { murmur: Math.cos(angle), unrest: Math.sin(angle), roar: 0 };
  }
  const t = (clamped - 0.5) / 0.5;
  const angle = t * (Math.PI / 2);
  return { murmur: 0, unrest: Math.cos(angle), roar: Math.sin(angle) };
}

export default function DevCrowdScreen() {
  const [started, setStarted] = useState(false);
  const [intensity, setIntensity] = useState(0.5);
  const [ducked, setDucked] = useState(false);
  const [loadErrors, setLoadErrors] = useState<string[]>([]);

  const ctxRef = useRef<AudioContext | null>(null);
  const bedGainRef = useRef<GainNode | null>(null);
  const loopGainsRef = useRef<Record<LoopName, GainNode> | null>(null);
  const oneShotBuffersRef = useRef<Partial<Record<OneShotName, AudioBuffer>>>({});
  const intensityRef = useRef(intensity);
  intensityRef.current = intensity;

  async function loadBuffer(ctx: AudioContext, name: string): Promise<AudioBuffer> {
    const res = await fetch(`/crowd/${name}.ogg`);
    if (!res.ok) {
      throw new Error(`${name}.ogg (${res.status})`);
    }
    const arrayBuffer = await res.arrayBuffer();
    return ctx.decodeAudioData(arrayBuffer);
  }

  async function handleStart() {
    const ctx = new AudioContext();
    ctxRef.current = ctx;

    const bedGain = ctx.createGain();
    bedGain.gain.value = 1;
    bedGain.connect(ctx.destination);
    bedGainRef.current = bedGain;

    const errors: string[] = [];
    const loopGains = {} as Record<LoopName, GainNode>;
    const gains = zoneGains(intensityRef.current);

    for (const name of LOOP_NAMES) {
      const gainNode = ctx.createGain();
      gainNode.gain.value = gains[name];
      gainNode.connect(bedGain);
      loopGains[name] = gainNode;
      try {
        const buffer = await loadBuffer(ctx, name);
        const source = ctx.createBufferSource();
        source.buffer = buffer;
        source.loop = true;
        source.connect(gainNode);
        source.start();
      } catch (err) {
        errors.push(`loop ${name}: ${(err as Error).message}`);
      }
    }
    loopGainsRef.current = loopGains;

    for (const name of ONE_SHOTS) {
      try {
        oneShotBuffersRef.current[name] = await loadBuffer(ctx, name);
      } catch (err) {
        errors.push(`one-shot ${name}: ${(err as Error).message}`);
      }
    }

    setLoadErrors(errors);
    setStarted(true);
  }

  function applyIntensity(next: number) {
    setIntensity(next);
    const ctx = ctxRef.current;
    const loopGains = loopGainsRef.current;
    if (!ctx || !loopGains) {
      return;
    }
    const gains = zoneGains(next);
    for (const name of LOOP_NAMES) {
      loopGains[name].gain.setValueAtTime(gains[name], ctx.currentTime);
    }
  }

  function playOneShot(name: OneShotName) {
    const ctx = ctxRef.current;
    const buffer = oneShotBuffersRef.current[name];
    if (!ctx || !buffer) {
      return;
    }
    const gainNode = ctx.createGain();
    gainNode.gain.value = Math.max(intensityRef.current, ONE_SHOT_MIN_GAIN);
    gainNode.connect(ctx.destination);
    const source = ctx.createBufferSource();
    source.buffer = buffer;
    source.connect(gainNode);
    source.start();
  }

  function toggleDuck() {
    const ctx = ctxRef.current;
    const bedGain = bedGainRef.current;
    if (!ctx || !bedGain) {
      return;
    }
    const next = !ducked;
    setDucked(next);
    const target = next ? DUCK_TARGET : 1;
    bedGain.gain.cancelScheduledValues(ctx.currentTime);
    bedGain.gain.setValueAtTime(bedGain.gain.value, ctx.currentTime);
    bedGain.gain.linearRampToValueAtTime(target, ctx.currentTime + DUCK_MS / 1000);
  }

  return (
    <div style={styles.container}>
      <h1 style={styles.title}>Πλήθος — crowd mix (dev only)</h1>
      <p style={styles.status}>
        Three loops (murmur / unrest / roar) crossfaded by intensity, plus four one-shots. Listening only — no game
        wiring (Task 36b). Files load from /crowd, gitignored; run{' '}
        <code style={styles.code}>tsx dev/generate-crowd-sfx.ts</code> first if this page is silent.
      </p>

      {!started ? (
        <button style={styles.startButton} onClick={handleStart}>
          Start
        </button>
      ) : (
        <>
          {loadErrors.length > 0 && (
            <div style={styles.errorBox}>
              {loadErrors.map((e) => (
                <div key={e}>{e}</div>
              ))}
            </div>
          )}

          <div style={styles.controlRow}>
            <label style={styles.label} htmlFor="intensity">
              Ένταση πλήθους: {intensity.toFixed(2)}
            </label>
            <input
              id="intensity"
              type="range"
              min={0}
              max={1}
              step={0.01}
              value={intensity}
              onChange={(e) => applyIntensity(Number(e.target.value))}
              style={styles.slider}
            />
            <div style={styles.zoneLabels}>
              <span>murmur</span>
              <span>unrest</span>
              <span>roar</span>
            </div>
          </div>

          <div style={styles.oneShotRow}>
            {ONE_SHOTS.map((name) => (
              <button key={name} style={styles.oneShotButton} onClick={() => playOneShot(name)}>
                {name}
              </button>
            ))}
          </div>

          <label style={styles.duckRow}>
            <input type="checkbox" checked={ducked} onChange={toggleDuck} />
            Duck (bed → 0.12 over 300ms)
          </label>
        </>
      )}
    </div>
  );
}

const styles: Record<string, CSSProperties> = {
  container: {
    minHeight: '100vh',
    background: 'var(--night-0)',
    color: 'var(--marble)',
    padding: '2rem',
    fontFamily: 'system-ui, sans-serif',
    display: 'flex',
    flexDirection: 'column',
    gap: '1.25rem',
    maxWidth: '640px',
  },
  title: {
    margin: 0,
    color: 'var(--ember)',
  },
  status: {
    margin: 0,
    color: 'var(--marble-2)',
    fontSize: '0.9rem',
    lineHeight: 1.5,
  },
  code: {
    background: 'var(--night-1)',
    padding: '0.1rem 0.35rem',
    borderRadius: '4px',
    color: 'var(--marble)',
  },
  startButton: {
    alignSelf: 'flex-start',
    background: 'var(--wine)',
    color: 'var(--marble)',
    border: '1px solid var(--wine-2)',
    borderRadius: '6px',
    padding: '0.6rem 1.4rem',
    fontSize: '1rem',
    cursor: 'pointer',
  },
  errorBox: {
    background: 'var(--night-1)',
    border: '1px solid var(--wine-2)',
    borderRadius: '6px',
    padding: '0.75rem 1rem',
    color: 'var(--marble-2)',
    fontSize: '0.85rem',
  },
  controlRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.4rem',
  },
  label: {
    color: 'var(--marble)',
  },
  slider: {
    width: '100%',
    accentColor: 'var(--ember)',
  },
  zoneLabels: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '0.75rem',
    color: 'var(--marble-3)',
  },
  oneShotRow: {
    display: 'flex',
    gap: '0.6rem',
    flexWrap: 'wrap',
  },
  oneShotButton: {
    background: 'var(--carve)',
    color: 'var(--marble)',
    border: '1px solid var(--marble-3)',
    borderRadius: '6px',
    padding: '0.5rem 0.9rem',
    fontSize: '0.85rem',
    cursor: 'pointer',
  },
  duckRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    color: 'var(--marble-2)',
    fontSize: '0.9rem',
  },
};
