import type { CSSProperties } from 'react';

export const QR_SIZE_PX = 240; // comfortably above the "at least 200px" floor

// React's CSSProperties doesn't model CSS custom properties - this lets the
// `--glow-color` variable the .glow/.glow-pulse classes read (see theme.css)
// be set inline per-element, since each glow needs a different colour.
export type CSSVars = CSSProperties & Record<`--${string}`, string>;

// "Slightly lighter panels with a subtle inner glow, so cards feel lit
// rather than painted on." Applied to every plain surface panel EXCEPT ones
// that also use the .glow/.glow-pulse classes - an inline boxShadow always
// wins over a CSS class's boxShadow, so combining the two would silently
// clobber the glow ring.
export const SURFACE_GLOW = 'inset 0 1px 0 rgba(255,255,255,0.06), inset 0 0 22px rgba(122,92,210,0.12)';

export const styles: Record<string, CSSProperties> = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '1.5rem',
    padding: '3rem 2rem',
    minHeight: '100vh',
    width: '100%',
    background: 'var(--bg)',
    color: 'var(--text)',
    // Stacks above the fixed .confetti-piece / .firework-particle layers
    // (both z-index: 0) regardless of DOM order. The background light
    // sweep this originally also stacked above (Task 21) was removed in
    // Task 22; the GAME_OVER light rays (Task 21) were removed in Task 23.
    position: 'relative',
    zIndex: 1,
  },
  status: { fontSize: '1.25rem', color: 'var(--text-faint)' },
  createButton: {
    fontSize: '2rem',
    padding: '1.5rem 3rem',
    borderRadius: '0.75rem',
    border: 'none',
    background: 'var(--gold)',
    color: '#14161c',
    fontWeight: 700,
  },
  createButtonDisabled: {
    fontSize: '2rem',
    padding: '1.5rem 3rem',
    borderRadius: '0.75rem',
    border: 'none',
    background: 'var(--border)',
    color: 'var(--text-faint)',
    fontWeight: 700,
  },
  code: {
    fontSize: '8rem',
    fontWeight: 700,
    fontFamily: 'monospace',
    letterSpacing: '0.5em',
    color: 'var(--gold)',
  },
  qrWrapper: {
    // Explicit white background regardless of theme - QR scanning fails on
    // dark/inverted codes on many phone cameras, so this can't just inherit
    // whatever the page background happens to be.
    background: '#ffffff',
    padding: '1rem',
    borderRadius: '1rem',
    lineHeight: 0,
  },
  muteToggle: {
    position: 'fixed',
    top: '1rem',
    left: '1rem',
    fontSize: '1.5rem',
    lineHeight: 1,
    background: 'var(--surface)',
    border: '1px solid var(--border-strong)',
    borderRadius: '999px',
    padding: '0.5rem 0.7rem',
    boxShadow: SURFACE_GLOW,
    cursor: 'pointer',
    zIndex: 50,
  },
  fullscreenToggle: {
    position: 'fixed',
    top: '1rem',
    right: '1rem',
    fontSize: '1.5rem',
    lineHeight: 1,
    background: 'var(--surface)',
    border: '1px solid var(--border-strong)',
    borderRadius: '999px',
    padding: '0.5rem 0.7rem',
    boxShadow: SURFACE_GLOW,
    cursor: 'pointer',
    zIndex: 50,
  },
  cornerRoomCode: {
    position: 'fixed',
    top: '1rem',
    right: '1rem',
    fontSize: '1rem',
    fontWeight: 700,
    fontFamily: 'monospace',
    letterSpacing: '0.15em',
    color: 'var(--text)',
    background: 'var(--surface)',
    border: '1px solid var(--border-strong)',
    padding: '0.35rem 0.75rem',
    borderRadius: '0.5rem',
    boxShadow: SURFACE_GLOW,
    // Above the pause overlay - players may still need the room code while
    // paused (e.g. someone new scanning the QR mid-break isn't possible,
    // but the code itself must never be hidden).
    zIndex: 50,
  },
  pauseOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(10, 7, 22, 0.92)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '1rem',
    zIndex: 40,
  },
  // Stage announcement (Task 31a). Sits ABOVE the pause overlay's z-index so
  // a stage entered while paused still reads, but below the corner room code
  // (50), which must never be covered.
  stageOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(10, 7, 22, 0.9)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2rem',
    zIndex: 45,
  },
  stageCard: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '1rem',
    textAlign: 'center',
    maxWidth: '80%',
  },
  stageKicker: {
    fontSize: '2rem',
    fontWeight: 700,
    letterSpacing: '0.3em',
    color: 'var(--gold)',
  },
  stageTitle: {
    fontSize: 'clamp(3.5rem, 6vw, 6rem)',
    fontWeight: 900,
    lineHeight: 1.15,
    color: 'var(--text)',
  },
  stageTagline: {
    fontSize: '2rem',
    fontWeight: 600,
    color: 'var(--text-dim)',
  },
  stageRange: {
    fontSize: '1.5rem',
    fontWeight: 600,
    color: 'var(--text-faint)',
  },
  pauseTitle: {
    fontSize: '5rem',
    fontWeight: 900,
    color: 'var(--text)',
    letterSpacing: '0.15em',
  },
  pauseSubtitle: {
    fontSize: '1.75rem',
    fontWeight: 600,
    color: 'var(--text-dim)',
  },
  counter: {
    fontSize: '2.5rem',
    fontWeight: 700,
    color: 'var(--text)',
  },
  playerList: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: '0.5rem',
    fontSize: '2.5rem',
    minHeight: '3rem',
    width: '100%',
    maxWidth: '640px',
  },
  playerRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.75rem',
  },
  playerName: {
    fontWeight: 600,
    color: 'var(--text)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    minWidth: 0,
  },
  playerNameDisconnected: {
    fontWeight: 600,
    color: 'var(--text-faint)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    minWidth: 0,
    opacity: 0.6,
  },
  waitingMessage: {
    fontSize: '2.5rem',
    fontWeight: 600,
    color: 'var(--text-dim)',
  },
  settingsSummary: {
    fontSize: '1.25rem',
    fontWeight: 600,
    color: 'var(--text-faint)',
  },
  category: {
    fontSize: '1.75rem',
    fontWeight: 600,
    color: 'var(--text-dim)',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  progress: {
    fontSize: '1.5rem',
    fontWeight: 600,
    color: 'var(--text-faint)',
  },
  questionText: {
    fontSize: '4rem',
    fontWeight: 700,
    textAlign: 'center',
    lineHeight: 1.3,
    maxWidth: '90%',
    color: 'var(--text)',
  },
  // QUESTION only. With the options gone (Task 29) the question is the
  // one thing to read on the TV, so it takes the space they used to.
  // clamp keeps the longest questions on screen at 1080p.
  questionTextTv: {
    fontSize: 'clamp(4rem, 6vw, 6rem)',
    fontWeight: 700,
    textAlign: 'center',
    lineHeight: 1.25,
    maxWidth: '85%',
    color: 'var(--text)',
  },
  optionsGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1.5rem',
    width: '100%',
    maxWidth: '1100px',
  },
  optionCard: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    fontSize: '2.25rem',
    fontWeight: 600,
    padding: '1.5rem 2rem',
    borderRadius: '1rem',
    background: 'var(--surface)',
    border: '3px solid var(--border)',
    color: 'var(--text)',
  },
  optionLabel: {
    fontWeight: 800,
    minWidth: '2rem',
  },
  timerRingWrap: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '7rem',
    height: '7rem',
    borderRadius: '50%',
    background: 'var(--surface)',
  },
  timer: {
    fontSize: '3rem',
    fontWeight: 800,
    fontFamily: 'monospace',
    color: 'var(--gold)',
  },
  answerCounter: {
    fontSize: '2rem',
    fontWeight: 700,
    color: 'var(--text-dim)',
  },
  answeredNames: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: '0.75rem',
    fontSize: '1.5rem',
    fontWeight: 600,
  },
  nameAnswered: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.4rem',
    color: 'var(--text)',
  },
  nameNotAnswered: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.4rem',
    color: 'var(--text-faint)',
  },
  optionCardCorrect: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    fontSize: '2.25rem',
    fontWeight: 700,
    padding: '1.5rem 2rem',
    borderRadius: '1rem',
    border: '3px solid',
    color: 'var(--text)',
  },
  optionCardWrong: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    fontSize: '2.25rem',
    fontWeight: 600,
    padding: '1.5rem 2rem',
    borderRadius: '1rem',
    background: 'var(--surface)',
    border: '3px solid',
    color: 'var(--text-faint)',
    opacity: 0.45,
    filter: 'grayscale(0.6)',
  },
  optionTextWrong: {
    color: 'var(--text-faint)',
  },
  answerCount: {
    marginLeft: 'auto',
    fontWeight: 800,
    color: 'var(--text-dim)',
  },
  gmLineBanner: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    padding: '0.6rem 1.5rem',
    borderRadius: '0.75rem',
    background: 'rgba(212, 175, 55, 0.12)',
    border: '2px solid var(--gold)',
    color: 'var(--gold)',
    fontSize: '1.35rem',
    fontWeight: 700,
    textAlign: 'center',
    width: '100%',
    maxWidth: '900px',
  },
  gmIntroBanner: {
    padding: '0.5rem 1.25rem',
    borderRadius: '0.75rem',
    background: 'rgba(212, 175, 55, 0.12)',
    border: '2px solid var(--gold)',
    color: 'var(--gold)',
    fontSize: '1.15rem',
    fontWeight: 700,
    textAlign: 'center',
    maxWidth: '700px',
  },
  revealStandingsStrip: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'baseline',
    gap: '0.5rem 1.25rem',
    width: '100%',
    maxWidth: '900px',
    fontSize: '1.1rem',
    fontWeight: 600,
    color: 'var(--text-dim)',
  },
  revealStandingsItem: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.4rem',
    whiteSpace: 'nowrap',
  },
  revealStandingsRank: {
    color: 'var(--gold)',
    fontWeight: 800,
  },
  revealStandingsName: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    maxWidth: '10rem',
  },
  revealStandingsScore: {
    fontFamily: 'monospace',
    color: 'var(--text)',
  },
  resultsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    width: '100%',
    maxWidth: '700px',
  },
  resultRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '0.75rem',
    fontSize: '1.75rem',
    fontWeight: 600,
    padding: '0.5rem 1rem',
  },
  resultRowFastest: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '0.75rem',
    fontSize: '1.9rem',
    fontWeight: 800,
    padding: '0.6rem 1.25rem',
    borderRadius: '0.75rem',
    background: 'rgba(212, 175, 55, 0.12)',
    border: '2px solid var(--gold)',
  },
  resultsDivider: {
    height: '1px',
    background: 'var(--border)',
    margin: '0.4rem 0',
  },
  resultNameCorrect: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.6rem',
    flex: 1,
    minWidth: 0,
    color: 'var(--success)',
  },
  resultNameWrong: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.6rem',
    flex: 1,
    minWidth: 0,
    // --danger-text, not --danger - the raw answer-A red hex drops under
    // 4.5:1 as small text on the new, lighter stage background.
    color: 'var(--danger-text)',
  },
  resultNameText: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    minWidth: 0,
  },
  resultPoints: {
    flexShrink: 0,
    fontFamily: 'monospace',
    fontWeight: 700,
    color: 'var(--text)',
  },
  standingsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
    width: '100%',
    maxWidth: '800px',
  },
  standingRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '1.5rem',
    fontSize: '2.25rem',
    fontWeight: 700,
    padding: '1rem 1.5rem',
    borderRadius: '0.75rem',
    background: 'var(--surface)',
    color: 'var(--text)',
  },
  standingRowDisconnected: {
    display: 'flex',
    alignItems: 'center',
    gap: '1.5rem',
    fontSize: '2.25rem',
    fontWeight: 700,
    padding: '1rem 1.5rem',
    borderRadius: '0.75rem',
    background: 'var(--surface)',
    color: 'var(--text-faint)',
    opacity: 0.5,
  },
  standingRowLeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '1.5rem',
    fontSize: '2.25rem',
    fontWeight: 700,
    padding: '1rem 1.5rem',
    borderRadius: '0.75rem',
    background: 'rgba(212, 175, 55, 0.1)',
    border: '2px solid var(--gold)',
    color: 'var(--text)',
  },
  standingRank: {
    color: 'var(--text-dim)',
    minWidth: '3rem',
  },
  standingName: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  standingScore: {
    flexShrink: 0,
    fontFamily: 'monospace',
  },
  gameOverTitleWrap: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '1rem',
    padding: '1.5rem 0',
  },
  winnerAvatarRow: {
    display: 'flex',
    justifyContent: 'center',
    gap: '1.5rem',
  },
  gameOverTitle: {
    position: 'relative',
    zIndex: 1,
    fontSize: '2.5rem',
    fontWeight: 700,
    color: 'var(--text-dim)',
  },
  winnerBanner: {
    position: 'relative',
    zIndex: 1,
    fontSize: '3.5rem',
    fontWeight: 800,
    color: 'var(--gold)',
    textAlign: 'center',
  },
  standingRowWinner: {
    display: 'flex',
    alignItems: 'center',
    gap: '1.5rem',
    fontSize: '2.25rem',
    fontWeight: 700,
    padding: '1rem 1.5rem',
    borderRadius: '0.75rem',
    background: 'rgba(212, 175, 55, 0.14)',
    border: '3px solid var(--gold)',
    color: 'var(--text)',
  },
  wakeLockHint: {
    fontSize: '0.9rem',
    color: 'var(--text-faint)',
  },
  powerHint: {
    fontSize: '0.85rem',
    color: 'var(--text-faint)',
    textAlign: 'center',
    cursor: 'pointer',
    maxWidth: '32rem',
  },
  powerHintDismiss: {
    fontWeight: 700,
  },
  progressBarTrack: {
    width: '100%',
    maxWidth: '500px',
    height: '0.5rem',
    borderRadius: '999px',
    background: 'var(--border)',
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    background: 'var(--gold)',
    borderRadius: '999px',
    transition: 'width 1s linear',
  },
  // Steal (Task 32) - the TV during and after a theft.
  stealThiefRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '1.25rem',
    fontSize: '3rem',
    fontWeight: 800,
    color: 'var(--gold)',
  },
  stealAmount: {
    fontSize: '2.25rem',
    fontWeight: 700,
    color: 'var(--text-dim)',
  },
  stealVictimRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '1.25rem',
    fontSize: '2.5rem',
    fontWeight: 700,
    color: 'var(--text)',
  },
  stealMovedAmount: {
    fontSize: 'clamp(4rem, 7vw, 7rem)',
    fontWeight: 800,
    color: 'var(--gold)',
  },
  stealNothing: {
    fontSize: '3rem',
    fontWeight: 700,
    color: 'var(--text-faint)',
  },
  stealClampNote: {
    fontSize: '1.5rem',
    fontWeight: 600,
    color: 'var(--text-faint)',
  },
  stealScoreLine: {
    fontSize: '1.75rem',
    fontWeight: 600,
    color: 'var(--text-dim)',
  },
};
